name: Build Mac ARM64

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-mac-arm:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16


      - name: Install dependencies
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          yarn install --ignore-engines

      - name: Build OpenMTP (main & renderer)
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          yarn build

      - name: Package Mac ARM64
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          export CSC_IDENTITY_AUTO_DISCOVERY=false
          yarn package-mac-arm64-without-notarize

      - name: Upload Mac ARM64 DMG and ZIP Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenMTP-mac-arm64
          path: |
            dist/*.dmg
            dist/*.zip
